name = "portfolio-website"
type = "javascript"
compatibility_date = "2024-12-10"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.html"]

[build.upload]
format = "modules"
directory = "dist/portfolio-website/browser"
